!****	KLDDT.CTL	MAY-78
!*****	ASSEMBLE PROGRAM
MAC::@R MACRO
*KLDDT@
@IF (ERROR) @GOTO BLO
LNK::@RUN DLINK
*KLDDT.SAV/SAV=KLDDT/NOSYM/NOINIT/GO
@IF (ERROR) @GOTO BLO
CRF::@R CREF
*KLDDT.LST=KLDDT
@IF (ERROR) @GOTO BLO
DC2::@RUN DECDOC.SAV
*KLDDT/S=KLDDT.TXT,KLDDT.HLP,KLDDT.HST,KLDDT.LST
@IF (ERROR) @GOTO BLO
DEL::@DEL KLDDT.LST,KLDDT.REL
@IF (ERROR) @GOTO BLO
CNV::@RUN CONVRT.SAV
*KLDDT
@IF (ERROR) @GOTO BLO
@GOTO LOG
!
BLO::@R PIP
*KLDDT.BLO=NUL:FOO
LOG::
